[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "plcIntegrator"
authors = [{name = "Simon JÃ¤ger", email = "simon.jager@ess.eu"}]
dynamic = ["version", "description"]
